name: fast_food_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  location: ^7.0.0
  flutter_polyline_points: ^2.1.0
  pinput: ^5.0.0
  flutter_multi_formatter: ^2.13.0
  svg_flutter: ^0.0.1
  yandex_mapkit: ^4.1.0
  dio: ^5.7.0
  get_it: ^8.0.0
  shared_preferences: ^2.3.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  mask_text_input_formatter: ^2.9.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/
    - .env

  # fonts:
  #   - family: inria_Sans
  #     fonts:
  #       - assets: fonts/inriaSans/InriaSans-Bold.ttf 
  #       - assets: fonts/inriaSans/InriaSans-BoldItalic.ttf 
  #       - assets: fonts/inriaSans/InriaSans-Italic.ttf 
  #       - assets: fonts/inriaSans/InriaSans-Light.ttf 
  #       - assets: fonts/inriaSans/InriaSans-LightItalic.ttf 
  #       - assets: fonts/inriaSans/InriaSans-Regular.ttf
