name: fast_food_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
 
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  location: ^7.0.0
  google_maps_flutter: ^2.7.0
  google_places_autocomplete_text_field: ^0.1.3
  flutter_polyline_points: ^2.1.0
  flutter_dotenv: ^5.1.0
  pinput: ^5.0.0
  flutter_multi_formatter: ^2.13.0
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: inria_Sans
      fonts:
        - asset: fonts/inriaSans/InriaSans-Bold.ttf 
        - asset: fonts/inriaSans/InriaSans-BoldItalic.ttf 
        - asset: fonts/inriaSans/InriaSans-Italic.ttf 
        - asset: fonts/inriaSans/InriaSans-Light.ttf 
        - asset: fonts/inriaSans/InriaSans-LightItalic.ttf 
        - asset: fonts/inriaSans/InriaSans-Regular.ttf
  # You can add more font families below if needed
